
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SimState` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SimState
 * 
 */
export type SimStateModel = runtime.Types.Result.DefaultSelection<Prisma.$SimStatePayload>

export type AggregateSimState = {
  _count: SimStateCountAggregateOutputType | null
  _min: SimStateMinAggregateOutputType | null
  _max: SimStateMaxAggregateOutputType | null
}

export type SimStateMinAggregateOutputType = {
  id: string | null
  name: string | null
  parameters: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SimStateMaxAggregateOutputType = {
  id: string | null
  name: string | null
  parameters: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SimStateCountAggregateOutputType = {
  id: number
  name: number
  parameters: number
  userId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SimStateMinAggregateInputType = {
  id?: true
  name?: true
  parameters?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type SimStateMaxAggregateInputType = {
  id?: true
  name?: true
  parameters?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type SimStateCountAggregateInputType = {
  id?: true
  name?: true
  parameters?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SimStateAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SimState to aggregate.
   */
  where?: Prisma.SimStateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SimStates to fetch.
   */
  orderBy?: Prisma.SimStateOrderByWithRelationInput | Prisma.SimStateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SimStateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SimStates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SimStates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SimStates
  **/
  _count?: true | SimStateCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SimStateMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SimStateMaxAggregateInputType
}

export type GetSimStateAggregateType<T extends SimStateAggregateArgs> = {
      [P in keyof T & keyof AggregateSimState]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSimState[P]>
    : Prisma.GetScalarType<T[P], AggregateSimState[P]>
}




export type SimStateGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SimStateWhereInput
  orderBy?: Prisma.SimStateOrderByWithAggregationInput | Prisma.SimStateOrderByWithAggregationInput[]
  by: Prisma.SimStateScalarFieldEnum[] | Prisma.SimStateScalarFieldEnum
  having?: Prisma.SimStateScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SimStateCountAggregateInputType | true
  _min?: SimStateMinAggregateInputType
  _max?: SimStateMaxAggregateInputType
}

export type SimStateGroupByOutputType = {
  id: string
  name: string
  parameters: string
  userId: string
  createdAt: Date
  updatedAt: Date
  _count: SimStateCountAggregateOutputType | null
  _min: SimStateMinAggregateOutputType | null
  _max: SimStateMaxAggregateOutputType | null
}

export type GetSimStateGroupByPayload<T extends SimStateGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SimStateGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SimStateGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SimStateGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SimStateGroupByOutputType[P]>
      }
    >
  >



export type SimStateWhereInput = {
  AND?: Prisma.SimStateWhereInput | Prisma.SimStateWhereInput[]
  OR?: Prisma.SimStateWhereInput[]
  NOT?: Prisma.SimStateWhereInput | Prisma.SimStateWhereInput[]
  id?: Prisma.StringFilter<"SimState"> | string
  name?: Prisma.StringFilter<"SimState"> | string
  parameters?: Prisma.StringFilter<"SimState"> | string
  userId?: Prisma.StringFilter<"SimState"> | string
  createdAt?: Prisma.DateTimeFilter<"SimState"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SimState"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type SimStateOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parameters?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type SimStateWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SimStateWhereInput | Prisma.SimStateWhereInput[]
  OR?: Prisma.SimStateWhereInput[]
  NOT?: Prisma.SimStateWhereInput | Prisma.SimStateWhereInput[]
  name?: Prisma.StringFilter<"SimState"> | string
  parameters?: Prisma.StringFilter<"SimState"> | string
  userId?: Prisma.StringFilter<"SimState"> | string
  createdAt?: Prisma.DateTimeFilter<"SimState"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SimState"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type SimStateOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parameters?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SimStateCountOrderByAggregateInput
  _max?: Prisma.SimStateMaxOrderByAggregateInput
  _min?: Prisma.SimStateMinOrderByAggregateInput
}

export type SimStateScalarWhereWithAggregatesInput = {
  AND?: Prisma.SimStateScalarWhereWithAggregatesInput | Prisma.SimStateScalarWhereWithAggregatesInput[]
  OR?: Prisma.SimStateScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SimStateScalarWhereWithAggregatesInput | Prisma.SimStateScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SimState"> | string
  name?: Prisma.StringWithAggregatesFilter<"SimState"> | string
  parameters?: Prisma.StringWithAggregatesFilter<"SimState"> | string
  userId?: Prisma.StringWithAggregatesFilter<"SimState"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SimState"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SimState"> | Date | string
}

export type SimStateCreateInput = {
  id?: string
  name: string
  parameters: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSimStatesInput
}

export type SimStateUncheckedCreateInput = {
  id?: string
  name: string
  parameters: string
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SimStateUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parameters?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSimStatesNestedInput
}

export type SimStateUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parameters?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SimStateCreateManyInput = {
  id?: string
  name: string
  parameters: string
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SimStateUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parameters?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SimStateUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parameters?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SimStateListRelationFilter = {
  every?: Prisma.SimStateWhereInput
  some?: Prisma.SimStateWhereInput
  none?: Prisma.SimStateWhereInput
}

export type SimStateOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SimStateCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parameters?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SimStateMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parameters?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SimStateMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parameters?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SimStateCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SimStateCreateWithoutUserInput, Prisma.SimStateUncheckedCreateWithoutUserInput> | Prisma.SimStateCreateWithoutUserInput[] | Prisma.SimStateUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SimStateCreateOrConnectWithoutUserInput | Prisma.SimStateCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SimStateCreateManyUserInputEnvelope
  connect?: Prisma.SimStateWhereUniqueInput | Prisma.SimStateWhereUniqueInput[]
}

export type SimStateUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SimStateCreateWithoutUserInput, Prisma.SimStateUncheckedCreateWithoutUserInput> | Prisma.SimStateCreateWithoutUserInput[] | Prisma.SimStateUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SimStateCreateOrConnectWithoutUserInput | Prisma.SimStateCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SimStateCreateManyUserInputEnvelope
  connect?: Prisma.SimStateWhereUniqueInput | Prisma.SimStateWhereUniqueInput[]
}

export type SimStateUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SimStateCreateWithoutUserInput, Prisma.SimStateUncheckedCreateWithoutUserInput> | Prisma.SimStateCreateWithoutUserInput[] | Prisma.SimStateUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SimStateCreateOrConnectWithoutUserInput | Prisma.SimStateCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SimStateUpsertWithWhereUniqueWithoutUserInput | Prisma.SimStateUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SimStateCreateManyUserInputEnvelope
  set?: Prisma.SimStateWhereUniqueInput | Prisma.SimStateWhereUniqueInput[]
  disconnect?: Prisma.SimStateWhereUniqueInput | Prisma.SimStateWhereUniqueInput[]
  delete?: Prisma.SimStateWhereUniqueInput | Prisma.SimStateWhereUniqueInput[]
  connect?: Prisma.SimStateWhereUniqueInput | Prisma.SimStateWhereUniqueInput[]
  update?: Prisma.SimStateUpdateWithWhereUniqueWithoutUserInput | Prisma.SimStateUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SimStateUpdateManyWithWhereWithoutUserInput | Prisma.SimStateUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SimStateScalarWhereInput | Prisma.SimStateScalarWhereInput[]
}

export type SimStateUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SimStateCreateWithoutUserInput, Prisma.SimStateUncheckedCreateWithoutUserInput> | Prisma.SimStateCreateWithoutUserInput[] | Prisma.SimStateUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SimStateCreateOrConnectWithoutUserInput | Prisma.SimStateCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SimStateUpsertWithWhereUniqueWithoutUserInput | Prisma.SimStateUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SimStateCreateManyUserInputEnvelope
  set?: Prisma.SimStateWhereUniqueInput | Prisma.SimStateWhereUniqueInput[]
  disconnect?: Prisma.SimStateWhereUniqueInput | Prisma.SimStateWhereUniqueInput[]
  delete?: Prisma.SimStateWhereUniqueInput | Prisma.SimStateWhereUniqueInput[]
  connect?: Prisma.SimStateWhereUniqueInput | Prisma.SimStateWhereUniqueInput[]
  update?: Prisma.SimStateUpdateWithWhereUniqueWithoutUserInput | Prisma.SimStateUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SimStateUpdateManyWithWhereWithoutUserInput | Prisma.SimStateUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SimStateScalarWhereInput | Prisma.SimStateScalarWhereInput[]
}

export type SimStateCreateWithoutUserInput = {
  id?: string
  name: string
  parameters: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SimStateUncheckedCreateWithoutUserInput = {
  id?: string
  name: string
  parameters: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SimStateCreateOrConnectWithoutUserInput = {
  where: Prisma.SimStateWhereUniqueInput
  create: Prisma.XOR<Prisma.SimStateCreateWithoutUserInput, Prisma.SimStateUncheckedCreateWithoutUserInput>
}

export type SimStateCreateManyUserInputEnvelope = {
  data: Prisma.SimStateCreateManyUserInput | Prisma.SimStateCreateManyUserInput[]
}

export type SimStateUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.SimStateWhereUniqueInput
  update: Prisma.XOR<Prisma.SimStateUpdateWithoutUserInput, Prisma.SimStateUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.SimStateCreateWithoutUserInput, Prisma.SimStateUncheckedCreateWithoutUserInput>
}

export type SimStateUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.SimStateWhereUniqueInput
  data: Prisma.XOR<Prisma.SimStateUpdateWithoutUserInput, Prisma.SimStateUncheckedUpdateWithoutUserInput>
}

export type SimStateUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SimStateScalarWhereInput
  data: Prisma.XOR<Prisma.SimStateUpdateManyMutationInput, Prisma.SimStateUncheckedUpdateManyWithoutUserInput>
}

export type SimStateScalarWhereInput = {
  AND?: Prisma.SimStateScalarWhereInput | Prisma.SimStateScalarWhereInput[]
  OR?: Prisma.SimStateScalarWhereInput[]
  NOT?: Prisma.SimStateScalarWhereInput | Prisma.SimStateScalarWhereInput[]
  id?: Prisma.StringFilter<"SimState"> | string
  name?: Prisma.StringFilter<"SimState"> | string
  parameters?: Prisma.StringFilter<"SimState"> | string
  userId?: Prisma.StringFilter<"SimState"> | string
  createdAt?: Prisma.DateTimeFilter<"SimState"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SimState"> | Date | string
}

export type SimStateCreateManyUserInput = {
  id?: string
  name: string
  parameters: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SimStateUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parameters?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SimStateUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parameters?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SimStateUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parameters?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SimStateSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  parameters?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["simState"]>

export type SimStateSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  parameters?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["simState"]>

export type SimStateSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  parameters?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["simState"]>

export type SimStateSelectScalar = {
  id?: boolean
  name?: boolean
  parameters?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SimStateOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "parameters" | "userId" | "createdAt" | "updatedAt", ExtArgs["result"]["simState"]>
export type SimStateInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SimStateIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SimStateIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $SimStatePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SimState"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    parameters: string
    userId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["simState"]>
  composites: {}
}

export type SimStateGetPayload<S extends boolean | null | undefined | SimStateDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SimStatePayload, S>

export type SimStateCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SimStateFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SimStateCountAggregateInputType | true
  }

export interface SimStateDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SimState'], meta: { name: 'SimState' } }
  /**
   * Find zero or one SimState that matches the filter.
   * @param {SimStateFindUniqueArgs} args - Arguments to find a SimState
   * @example
   * // Get one SimState
   * const simState = await prisma.simState.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SimStateFindUniqueArgs>(args: Prisma.SelectSubset<T, SimStateFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SimStateClient<runtime.Types.Result.GetResult<Prisma.$SimStatePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SimState that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SimStateFindUniqueOrThrowArgs} args - Arguments to find a SimState
   * @example
   * // Get one SimState
   * const simState = await prisma.simState.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SimStateFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SimStateFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SimStateClient<runtime.Types.Result.GetResult<Prisma.$SimStatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SimState that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SimStateFindFirstArgs} args - Arguments to find a SimState
   * @example
   * // Get one SimState
   * const simState = await prisma.simState.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SimStateFindFirstArgs>(args?: Prisma.SelectSubset<T, SimStateFindFirstArgs<ExtArgs>>): Prisma.Prisma__SimStateClient<runtime.Types.Result.GetResult<Prisma.$SimStatePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SimState that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SimStateFindFirstOrThrowArgs} args - Arguments to find a SimState
   * @example
   * // Get one SimState
   * const simState = await prisma.simState.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SimStateFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SimStateFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SimStateClient<runtime.Types.Result.GetResult<Prisma.$SimStatePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SimStates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SimStateFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SimStates
   * const simStates = await prisma.simState.findMany()
   * 
   * // Get first 10 SimStates
   * const simStates = await prisma.simState.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const simStateWithIdOnly = await prisma.simState.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SimStateFindManyArgs>(args?: Prisma.SelectSubset<T, SimStateFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SimStatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SimState.
   * @param {SimStateCreateArgs} args - Arguments to create a SimState.
   * @example
   * // Create one SimState
   * const SimState = await prisma.simState.create({
   *   data: {
   *     // ... data to create a SimState
   *   }
   * })
   * 
   */
  create<T extends SimStateCreateArgs>(args: Prisma.SelectSubset<T, SimStateCreateArgs<ExtArgs>>): Prisma.Prisma__SimStateClient<runtime.Types.Result.GetResult<Prisma.$SimStatePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SimStates.
   * @param {SimStateCreateManyArgs} args - Arguments to create many SimStates.
   * @example
   * // Create many SimStates
   * const simState = await prisma.simState.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SimStateCreateManyArgs>(args?: Prisma.SelectSubset<T, SimStateCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SimStates and returns the data saved in the database.
   * @param {SimStateCreateManyAndReturnArgs} args - Arguments to create many SimStates.
   * @example
   * // Create many SimStates
   * const simState = await prisma.simState.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SimStates and only return the `id`
   * const simStateWithIdOnly = await prisma.simState.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SimStateCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SimStateCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SimStatePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SimState.
   * @param {SimStateDeleteArgs} args - Arguments to delete one SimState.
   * @example
   * // Delete one SimState
   * const SimState = await prisma.simState.delete({
   *   where: {
   *     // ... filter to delete one SimState
   *   }
   * })
   * 
   */
  delete<T extends SimStateDeleteArgs>(args: Prisma.SelectSubset<T, SimStateDeleteArgs<ExtArgs>>): Prisma.Prisma__SimStateClient<runtime.Types.Result.GetResult<Prisma.$SimStatePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SimState.
   * @param {SimStateUpdateArgs} args - Arguments to update one SimState.
   * @example
   * // Update one SimState
   * const simState = await prisma.simState.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SimStateUpdateArgs>(args: Prisma.SelectSubset<T, SimStateUpdateArgs<ExtArgs>>): Prisma.Prisma__SimStateClient<runtime.Types.Result.GetResult<Prisma.$SimStatePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SimStates.
   * @param {SimStateDeleteManyArgs} args - Arguments to filter SimStates to delete.
   * @example
   * // Delete a few SimStates
   * const { count } = await prisma.simState.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SimStateDeleteManyArgs>(args?: Prisma.SelectSubset<T, SimStateDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SimStates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SimStateUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SimStates
   * const simState = await prisma.simState.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SimStateUpdateManyArgs>(args: Prisma.SelectSubset<T, SimStateUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SimStates and returns the data updated in the database.
   * @param {SimStateUpdateManyAndReturnArgs} args - Arguments to update many SimStates.
   * @example
   * // Update many SimStates
   * const simState = await prisma.simState.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SimStates and only return the `id`
   * const simStateWithIdOnly = await prisma.simState.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SimStateUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SimStateUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SimStatePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SimState.
   * @param {SimStateUpsertArgs} args - Arguments to update or create a SimState.
   * @example
   * // Update or create a SimState
   * const simState = await prisma.simState.upsert({
   *   create: {
   *     // ... data to create a SimState
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SimState we want to update
   *   }
   * })
   */
  upsert<T extends SimStateUpsertArgs>(args: Prisma.SelectSubset<T, SimStateUpsertArgs<ExtArgs>>): Prisma.Prisma__SimStateClient<runtime.Types.Result.GetResult<Prisma.$SimStatePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SimStates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SimStateCountArgs} args - Arguments to filter SimStates to count.
   * @example
   * // Count the number of SimStates
   * const count = await prisma.simState.count({
   *   where: {
   *     // ... the filter for the SimStates we want to count
   *   }
   * })
  **/
  count<T extends SimStateCountArgs>(
    args?: Prisma.Subset<T, SimStateCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SimStateCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SimState.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SimStateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SimStateAggregateArgs>(args: Prisma.Subset<T, SimStateAggregateArgs>): Prisma.PrismaPromise<GetSimStateAggregateType<T>>

  /**
   * Group by SimState.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SimStateGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SimStateGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SimStateGroupByArgs['orderBy'] }
      : { orderBy?: SimStateGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SimStateGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSimStateGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SimState model
 */
readonly fields: SimStateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SimState.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SimStateClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SimState model
 */
export interface SimStateFieldRefs {
  readonly id: Prisma.FieldRef<"SimState", 'String'>
  readonly name: Prisma.FieldRef<"SimState", 'String'>
  readonly parameters: Prisma.FieldRef<"SimState", 'String'>
  readonly userId: Prisma.FieldRef<"SimState", 'String'>
  readonly createdAt: Prisma.FieldRef<"SimState", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SimState", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SimState findUnique
 */
export type SimStateFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SimState
   */
  select?: Prisma.SimStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SimState
   */
  omit?: Prisma.SimStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SimStateInclude<ExtArgs> | null
  /**
   * Filter, which SimState to fetch.
   */
  where: Prisma.SimStateWhereUniqueInput
}

/**
 * SimState findUniqueOrThrow
 */
export type SimStateFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SimState
   */
  select?: Prisma.SimStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SimState
   */
  omit?: Prisma.SimStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SimStateInclude<ExtArgs> | null
  /**
   * Filter, which SimState to fetch.
   */
  where: Prisma.SimStateWhereUniqueInput
}

/**
 * SimState findFirst
 */
export type SimStateFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SimState
   */
  select?: Prisma.SimStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SimState
   */
  omit?: Prisma.SimStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SimStateInclude<ExtArgs> | null
  /**
   * Filter, which SimState to fetch.
   */
  where?: Prisma.SimStateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SimStates to fetch.
   */
  orderBy?: Prisma.SimStateOrderByWithRelationInput | Prisma.SimStateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SimStates.
   */
  cursor?: Prisma.SimStateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SimStates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SimStates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SimStates.
   */
  distinct?: Prisma.SimStateScalarFieldEnum | Prisma.SimStateScalarFieldEnum[]
}

/**
 * SimState findFirstOrThrow
 */
export type SimStateFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SimState
   */
  select?: Prisma.SimStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SimState
   */
  omit?: Prisma.SimStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SimStateInclude<ExtArgs> | null
  /**
   * Filter, which SimState to fetch.
   */
  where?: Prisma.SimStateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SimStates to fetch.
   */
  orderBy?: Prisma.SimStateOrderByWithRelationInput | Prisma.SimStateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SimStates.
   */
  cursor?: Prisma.SimStateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SimStates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SimStates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SimStates.
   */
  distinct?: Prisma.SimStateScalarFieldEnum | Prisma.SimStateScalarFieldEnum[]
}

/**
 * SimState findMany
 */
export type SimStateFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SimState
   */
  select?: Prisma.SimStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SimState
   */
  omit?: Prisma.SimStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SimStateInclude<ExtArgs> | null
  /**
   * Filter, which SimStates to fetch.
   */
  where?: Prisma.SimStateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SimStates to fetch.
   */
  orderBy?: Prisma.SimStateOrderByWithRelationInput | Prisma.SimStateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SimStates.
   */
  cursor?: Prisma.SimStateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SimStates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SimStates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SimStates.
   */
  distinct?: Prisma.SimStateScalarFieldEnum | Prisma.SimStateScalarFieldEnum[]
}

/**
 * SimState create
 */
export type SimStateCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SimState
   */
  select?: Prisma.SimStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SimState
   */
  omit?: Prisma.SimStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SimStateInclude<ExtArgs> | null
  /**
   * The data needed to create a SimState.
   */
  data: Prisma.XOR<Prisma.SimStateCreateInput, Prisma.SimStateUncheckedCreateInput>
}

/**
 * SimState createMany
 */
export type SimStateCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SimStates.
   */
  data: Prisma.SimStateCreateManyInput | Prisma.SimStateCreateManyInput[]
}

/**
 * SimState createManyAndReturn
 */
export type SimStateCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SimState
   */
  select?: Prisma.SimStateSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SimState
   */
  omit?: Prisma.SimStateOmit<ExtArgs> | null
  /**
   * The data used to create many SimStates.
   */
  data: Prisma.SimStateCreateManyInput | Prisma.SimStateCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SimStateIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SimState update
 */
export type SimStateUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SimState
   */
  select?: Prisma.SimStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SimState
   */
  omit?: Prisma.SimStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SimStateInclude<ExtArgs> | null
  /**
   * The data needed to update a SimState.
   */
  data: Prisma.XOR<Prisma.SimStateUpdateInput, Prisma.SimStateUncheckedUpdateInput>
  /**
   * Choose, which SimState to update.
   */
  where: Prisma.SimStateWhereUniqueInput
}

/**
 * SimState updateMany
 */
export type SimStateUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SimStates.
   */
  data: Prisma.XOR<Prisma.SimStateUpdateManyMutationInput, Prisma.SimStateUncheckedUpdateManyInput>
  /**
   * Filter which SimStates to update
   */
  where?: Prisma.SimStateWhereInput
  /**
   * Limit how many SimStates to update.
   */
  limit?: number
}

/**
 * SimState updateManyAndReturn
 */
export type SimStateUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SimState
   */
  select?: Prisma.SimStateSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SimState
   */
  omit?: Prisma.SimStateOmit<ExtArgs> | null
  /**
   * The data used to update SimStates.
   */
  data: Prisma.XOR<Prisma.SimStateUpdateManyMutationInput, Prisma.SimStateUncheckedUpdateManyInput>
  /**
   * Filter which SimStates to update
   */
  where?: Prisma.SimStateWhereInput
  /**
   * Limit how many SimStates to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SimStateIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SimState upsert
 */
export type SimStateUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SimState
   */
  select?: Prisma.SimStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SimState
   */
  omit?: Prisma.SimStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SimStateInclude<ExtArgs> | null
  /**
   * The filter to search for the SimState to update in case it exists.
   */
  where: Prisma.SimStateWhereUniqueInput
  /**
   * In case the SimState found by the `where` argument doesn't exist, create a new SimState with this data.
   */
  create: Prisma.XOR<Prisma.SimStateCreateInput, Prisma.SimStateUncheckedCreateInput>
  /**
   * In case the SimState was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SimStateUpdateInput, Prisma.SimStateUncheckedUpdateInput>
}

/**
 * SimState delete
 */
export type SimStateDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SimState
   */
  select?: Prisma.SimStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SimState
   */
  omit?: Prisma.SimStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SimStateInclude<ExtArgs> | null
  /**
   * Filter which SimState to delete.
   */
  where: Prisma.SimStateWhereUniqueInput
}

/**
 * SimState deleteMany
 */
export type SimStateDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SimStates to delete
   */
  where?: Prisma.SimStateWhereInput
  /**
   * Limit how many SimStates to delete.
   */
  limit?: number
}

/**
 * SimState without action
 */
export type SimStateDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SimState
   */
  select?: Prisma.SimStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SimState
   */
  omit?: Prisma.SimStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SimStateInclude<ExtArgs> | null
}
